version: "3"
services:
  db:
    image: postgres:11
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: userbook